version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: ax_backend
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: development
      # Load DB_* and DATABASE_URL from /app/.env (mounted) instead of compose env
      JWT_SECRET: ${JWT_SECRET:-ax_stock_jwt_secret_2024}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-ax_stock_refresh_secret_2024}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      # Timezone settings
      TZ: Africa/Kigali
      APP_TZ: Africa/Kigali
      DB_TZ_OFFSET: "+02:00"
      API_VERSION: ${API_VERSION:-v1}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: ax_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001/api/${API_VERSION:-v1}
      REACT_APP_WS_URL: ws://localhost:3001
      TZ: Africa/Kigali
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ax_network

networks:
  ax_network:
    driver: bridge
